services:
  mongodb:
    image: mongo:latest
    container_name: reporte-mongodb
    environment:
      MONGO_INITDB_DATABASE: ${MONGO_DB_NAME:-report_db}
    ports:
      - "${MONGO_PORT:-27017}:27017"
    volumes:
      - reporte-mongodb-data:/data/db

volumes:
  reporte-mongodb-data:
