spring:
  application:
    name: microservicio-reporte
  jpa:
    hibernate:
      ddl-auto: validate
  data:
    mongodb:
      host: ${MONGODB_HOST:-localhost}
      port: ${MONGO_PORT:-27017}
      database: ${MONGO_DB_NAME:-report_db}
  security:
    user:
      name: admin
      password: ${ADMIN_PASSWORD:adminpassword}
      roles: ADMIN

server:
  port: 8085

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
